name: BuildOACdemo
on:
  workflow_dispatch:

permissions:
  attestations: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      CMAKE_GENERATOR_X86: "-G \"Visual Studio 17 2022\" -A Win32"
      CMAKE_GENERATOR_X64: "-G \"Visual Studio 17 2022\" -A x64"
      CMAKE_COMMON_DEFINES: "-DCMAKE_TOOLCHAIN_FILE=\"${{ github.workspace }}/src/msvc_flags.cmake\""

      OPUS_SOL_FILE: Oac.sln
      #OPUS_GIT_TAG: v1.6.1
      OPUS_CMAKE: "-DOPUS_BUILD_PROGRAMS=ON -DOPUS_DEEP_PLC=ON -DOPUS_DRED=ON -DOPUS_OSCE=ON -DOPUS_STATIC_RUNTIME=ON"
      OPUS_MSBUILD_CMD_X86: "/maxcpucount /property:Configuration=Release,Platform=Win32"
      OPUS_MSBUILD_CMD_X64: "/maxcpucount /property:Configuration=Release,Platform=x64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone repo
        run: |
          cd lib
          dir
          git clone https://github.com/AOMediaCodec/oac.git
          cd oac && dir
          
      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install NASM
        run: |
          curl -L -o "${{ runner.temp }}/nasm.zip" https://www.nasm.us/pub/nasm/releasebuilds/3.01/win64/nasm-3.01-win64.zip
          tar -xf "${{ runner.temp }}/nasm.zip" -C "${{ github.workspace }}/.."
          move "${{ github.workspace }}/../nasm-*" "${{ github.workspace }}/../nasm"
          Add-Content $env:GITHUB_PATH "${{ github.workspace }}/../nasm"

      - name: Check tools
        run: |
          7z
          cmake --version
          nasm --version
          msbuild --version

      - name: Prepare OAC
        run: |
          cd "lib\oac"
          git checkout tags/${{ env.OPUS_GIT_TAG }}
          & .\autogen.bat
          mkdir "_build" && cd "_build"
          mkdir "Win32" && cd "Win32"
          cmake ${{ env.CMAKE_GENERATOR_X86 }} ${{ env.CMAKE_COMMON_DEFINES }} ${{ env.OPUS_CMAKE }} ..\..\
          dir
          
          msbuild ${{ env.OPUS_SOL_FILE }} ${{ env.OPUS_MSBUILD_CMD_X86 }}
          cd ..
          mkdir "x64" && cd "x64"
          cmake ${{ env.CMAKE_GENERATOR_X64 }} ${{ env.CMAKE_COMMON_DEFINES }} ${{ env.OPUS_CMAKE }} ..\..\
          msbuild ${{ env.OPUS_SOL_FILE }} ${{ env.OPUS_MSBUILD_CMD_X64 }}

      - name: Prepare upload
        run: |
          mkdir "oac-demo\win32", "oac-demo\x64"
          copy "lib\opus\_build\Win32\Release\oac_*.exe" "oac-demo\win32"
          copy "lib\opus-tools\win32\VS2015\Win32\Release\oac*.exe" "oac-demo\win32"
          copy "lib\opus\_build\x64\Release\oac_*.exe" "oac-demo\x64"
          copy "lib\opus-tools\win32\VS2015\x64\Release\oac*.exe" "oac-demo\x64"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: oac-demo
          path: oac-demo
          compression-level: 9

      - name: Generate build provenace attestations
        uses: actions/attest@v4
        with:
          subject-path: oac-demo/**
